import streamlit as st
from vis_agent import VisAgent
from common import lookup_dataset_by_name, render_aggrid
st.title("Visualization Agent")
st.write()
"""
Ask any question about the data set and the agent will help visualize 

### Example prompts:
- Show the relationship between education and income.
- Compare the average hours worked per week by income group.
- What is the relationship between probability of earning a high income and race.
- Compare education level across countries.

### Tips
- Avoid asking multi-step, complex analytical questions
- Ask about specific columns in the datasets
"""

if "agent" not in st.session_state:
    st.session_state.agent = VisAgent()
prompt = st.chat_input("Ask your questions about the data...")
if prompt:
    st.chat_message("user").write(prompt)
    with st.spinner("Generating your visualization..."):
        answer = st.session_state.agent.run(prompt)
    if answer["status"] == 'error':
        st.error(answer["message"])
    else:
        chart = answer["chart_obj"]
        dataset_name = answer["dataset"]
        code = answer["code"]
        desc = answer["desc"]
        df = lookup_dataset_by_name(dataset_name)
        st.subheader("Your Visualization")
        st.altair_chart(chart, use_container_width = True)
        st.subheader("Description")
        st.write(desc)
        st.subheader("Code")
        st.code(code, language = "python")
        st.subheader("Dataset_Used")
        render_aggrid(df)
        st.caption("The visualization was generated by an LLM using Altair according to the user prompt")